language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pycodestyle --show-source onexone tests
  - nosetests -s --with-coverage --cover-branches --cover-erase --cover-html --cover-package=onexone
